name: Make booking

on:
  issues:
    types: [opened, reopened]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - name: Checkout ${{ github.sha }}
      uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install dependencies
      run: npm ci
      working-directory: ./src
    - name: Run
      run: node issue.js
      working-directory: ./src
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}